name: Build on Ubuntu 20.04

on:
  workflow_dispatch:
  push:
    branches: 
      - master
      - ci-fix 

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Prerequisites
      shell: bash
      run: sudo apt update && sudo apt install -y libgtest-dev libzmq3-dev libboost-system-dev libboost-thread-dev cmake pkg-config build-essential libudev-dev
      
    - name: Clone, Build & Install libusbp
      shell: bash
      run: git clone https://github.com/pololu/libusbp && cd libusbp && mkdir build && cd build && cmake .. && cmake --build . && sudo cmake --install .   

    - name: Build & Install libsubtractive
      run: cmake -E make_directory ./build && cd build && cmake .. && cmake --build . && sudo cmake --install .

    #- name: cmake
    #  shell: bash
    #  working-directory: ./build
    #  run: cmake ..
      
    #- name: cmake --build .
    #  shell: bash
    #  working-directory: ./build
    #  run: cmake --build .
      
    #- name: cmake --install .
    #  shell: bash
    #  working-directory: ./build
    #  run: sudo cmake --install .
