name: Build on Ubuntu 20.04

on:
  workflow_dispatch:
  push:
    branches: 
      - master
      - ci-fix 

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Prerequisites
      shell: bash
      run: sudo apt update && apt install -y libgtest-dev libzmq3-dev libboost-system-dev libboost-thread-dev cmake pkg-config build-essential libudev-dev
      
    - name: Install libusbp
      shell: bash
      run: git clone https://github.com/pololu/libusbp && cd libusbp && mkdir build && cd build && cmake .. && cmake --build . && sudo cmake --install .   
      
    #- name: Install Prerequisites
    #  shell: bash
    #  working-directory: ./scripts
    #  run: chmod u+x preinstall_ubuntu-2004.sh && ./preinstall_ubuntu-2004.sh 

    - name: Create Build Environment
      run: cmake -E make_directory ./build

    - name: cmake
      shell: bash
      working-directory: ./build
      run: cmake ..
      
    - name: cmake --build .
      shell: bash
      working-directory: ./build
      run: cmake --build .
      
    - name: cmake --install .
      shell: bash
      working-directory: ./build
      run: sudo cmake --install .

    #- name: sudo ldconfig
    #  shell: bash
    #  working-directory: ./build
    #  run: sudo ldconfig
      
    - name: test if exists
      shell: bash
      working-directory: ./build
      run: |
           pkgs='libsubtractive'
           if ! ldconfig -p | grep $pkgs >/dev/null 2>&1; then
                exit 1
            else
                echo 'success'
            fi
