name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install Prerequisites
      shell: bash
      working-directory: ./scripts
      run: chmod u+x preinstall_ubuntu-2004.sh && ./preinstall_ubuntu-2004.sh 

    - name: Create Build Environment
      run: cmake -E make_directory ./build

    - name: cmake
      shell: bash
      working-directory: ./build
      run: cmake ..
      
    - name: make
      shell: bash
      working-directory: ./build
      run: make
      
    - name: sudo make install
      shell: bash
      working-directory: ./build
      run: sudo make install

    - name: sudo ldconfig
      shell: bash
      working-directory: ./build
      run: sudo ldconfig
      
    - name: test if exists
      shell: bash
      working-directory: ./build
      run: |
           pkgs='libsubtractive'
           if ! ldconfig -p | grep $pkgs >/dev/null 2>&1; then
                exit 1
            else
                echo 'success'
            fi
    
    - name: cppcheck . --enable=all
      shell: bash
      working-directory: .
      run: cppcheck . --enable=all
            
    - uses: actions/upload-artifact@v2
      with: 
        name: upload libsubtractive_ubuntu-2004
        path: ./build
  
    - uses: actions/upload-artifact@v2
      with: 
        name: upload libsubtractive_ubuntu-2004_binaries
        path: | 
         /usr/local/lib/libsubtractive.so
         /usr/local/include/libsubtractive.hpp
         /usr/local/lib/pkgconfig/libsubtractive.pc

